# Generated by Django 5.0.4 on 2024-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('overall_score', models.FloatField()),
                ('technical_score', models.FloatField()),
                ('economic_score', models.FloatField()),
                ('environmental_score', models.FloatField()),
                ('installed_capacity', models.IntegerField()),
                ('generation_per_year', models.FloatField()),
            ],
        ),
    ]
