# Generated by Django 5.0.4 on 2024-04-11 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_resourceevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.site'),
        ),
    ]
