# Generated by Django 5.0.4 on 2024-04-11 06:27

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_analysis_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
