# Generated by Django 5.0.4 on 2024-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_resource_id_resource_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcevariable',
            old_name='variable_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_variables',
            field=models.ManyToManyField(related_name='variables', to='api.resourcevariable'),
        ),
    ]
