# Generated by Django 5.0.4 on 2024-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_variable_id_resourcevariable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcevariable',
            name='frequency',
            field=models.CharField(choices=[('Hourly', 'HOURLY'), ('Daily', 'DAILY'), ('Monthly', 'MONTHLY'), ('Yearly', 'YEARLY')], max_length=20),
        ),
    ]
