# Generated by Django 5.0.4 on 2024-04-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_source_remove_resource_resource_variables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeserie',
            name='variable_id',
        ),
        migrations.AddField(
            model_name='resourcevariable',
            name='time_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timeserie'),
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
