# Generated by Django 5.0.4 on 2024-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_timeserie_variable_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TimeSerie",
            new_name="TimeSeries",
        ),
        migrations.RemoveField(
            model_name="resourcevariable",
            name="time_series",
        ),
        migrations.AddField(
            model_name="resourcevariable",
            name="time_series",
            field=models.ManyToManyField(related_name="data", to="api.timeseries"),
        ),
    ]
