# Generated by Django 5.0.4 on 2024-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_timeseries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='variable', to='api.resourcevariable'),
        ),
    ]
