# Generated by Django 5.0.4 on 2024-04-11 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_site_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcevariable',
            name='date_added',
        ),
        migrations.AddField(
            model_name='resourcevariable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resourcevariable',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
