# Generated by Django 5.0.4 on 2024-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_resourcevariable_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcevariable',
            name='time_series',
            field=models.ManyToManyField(blank=True, related_name='data', to='api.timeseries'),
        ),
    ]
