# Generated by Django 5.0.4 on 2024-04-11 22:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_resourcevariable_time_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
