# Generated by Django 5.0.4 on 2024-04-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_resourcevariable_time_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcevariable',
            name='unit',
            field=models.CharField(choices=[('m/s', 'METER_PER_SECOND'), ('m^3/s', 'CUBIT_METER'), ('Celsius', 'CELSIUS'), ('Fahrenheit', 'FAHRENHEIT')], max_length=20),
        ),
    ]
